name: Deploy to AWS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.DEPLOY_KEY }}
          name: id_rsa
          known_hosts: 52.194.159.119

      - name: Deploy files to AWS
        run: |
          rsync -avz ./ ubuntu@52.194.159.119:/var/www/html/nycuaa.org/calendar
