name: Deploy to AWS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.DEPLOY_KEY }}
          name: nycuaa_ec2.pem
          known_hosts: '52.194.159.119:22211'

      - name: Check if SSH key file exists and print fingerprint
        run: |
          if [ -f ~/.ssh/nycuaa_ec2.pem ]; then
            echo "SSH key file exists."
            ssh-keygen -lf ~/.ssh/nycuaa_ec2.pem
          else
            echo "SSH key file is missing."
          fi

      - name: Deploy files to AWS
        run: |
          scp -P 22211 -i ~/.ssh/nycuaa_ec2.pem ./ ubuntu@52.194.159.119:/var/www/html/nycuaa.org/calendar
